### ISSUE TITLE
001 Bug Sidebar (Mobile)

### ISSUE THREAD

**Issue by Syaabill** [Syaabill/pengaduan-masyarakat#1]
Bug sidebar berada di tengah pada menu admin

<img width="425" alt="image" src="https://github.com/Syaabill/pengaduan-masyarakat/assets/93500382/83e2a29c-6bd8-49ca-9ee0-36a05bca16bd">

**Comment by opqdul** [comment]
#3 done bang, coba cek

**Comment by opqdul** [comment]
done lagi bang https://github.com/Syaabill/pengaduan-masyarakat/pull/5
